//go:build thirdparty

// This file is compiled only under the "thirdparty" build tag, so the default
// benchmark run stays offline with zero external dependencies. quicktemplate is
// the fastest COMPILED Go template engine: its idiomatic fast path is qtc-
// generated Go, so it is the right bar for Quill's compiled path (the
// BenchmarkCompiled* family), not the interpreted engines.
//
// The render functions live in package quillbench/qtpl, generated by qtc from
// qtpl/bench.qtpl and committed as qtpl/bench.qtpl.go. That generated file
// carries a "//go:build thirdparty" constraint (added by genqtpl.go) so the
// default offline build never compiles it and therefore never depends on
// quicktemplate. Regenerate with `cd bench && go generate ./...`.
//
//go:generate go run genqtpl.go

package quillbench

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"testing"

	"quillbench/qtpl"
)

// qtplRows builds n rows in the generated package's Row shape, mirroring
// records(n) for the stdlib engines so quicktemplate renders byte-identical
// output.
func qtplRows(n int) []qtpl.Row {
	rs := make([]qtpl.Row, n)
	for i := range rs {
		rs[i] = qtpl.Row{Name: "user", Email: "user@example.com"}
	}
	return rs
}

// ==================== quicktemplate (qtc-compiled) ====================
//
// quicktemplate has no "load" phase: the template is compiled to Go ahead of
// time by qtc, so there is only a render benchmark. WriteLoop/WriteTiny stream
// straight to an io.Writer, which is the fast path the engine is designed for.

func BenchmarkQuicktemplate_Tiny_Render(b *testing.B) {
	var buf bytes.Buffer
	qtpl.WriteTiny(&buf, "ada")
	b.SetBytes(int64(buf.Len()))
	b.ReportAllocs()
	for b.Loop() {
		qtpl.WriteTiny(io.Discard, "ada")
	}
}

// BenchmarkQuicktemplate_Loop_Render sweeps the loop row count so quicktemplate's
// scaling lines up column-for-column with the other engines' n=1..1000
// sub-benchmarks.
func BenchmarkQuicktemplate_Loop_Render(b *testing.B) {
	for _, n := range loopSizes {
		b.Run(fmt.Sprintf("n=%d", n), func(b *testing.B) {
			rows := qtplRows(n)
			var buf bytes.Buffer
			qtpl.WriteLoop(&buf, rows)
			b.SetBytes(int64(buf.Len()))
			b.ReportAllocs()
			for b.Loop() {
				qtpl.WriteLoop(io.Discard, rows)
			}
		})
	}
}

// qtplConstraint mirrors thirdpartyConstraint in genqtpl.go: the build tag
// genqtpl.go prepends to qtc's output. It is duplicated here so the staleness
// guard reproduces the committed file byte for byte without importing the
// //go:build ignore generator.
const qtplConstraint = "//go:build thirdparty\n\n"

// TestQuicktemplateGenIsCurrent regenerates the qtc render functions in place
// (qtc must run in this module so it can resolve its own package, and its
// //line directives are anchored to the "qtpl/bench.qtpl" source path, so a
// scratch copy would not reproduce the committed bytes), applies the same
// build-tag prefix genqtpl.go applies, and asserts the result is byte-identical
// to the committed qtpl/bench.qtpl.go. A template change that is not regenerated
// (or a qtc version bump) fails here rather than silently drifting. The committed
// file is restored afterward so the test never mutates the working tree. If the
// qtc toolchain is unavailable the test skips rather than failing spuriously.
func TestQuicktemplateGenIsCurrent(t *testing.T) {
	const genPath = "qtpl/bench.qtpl.go"
	committed, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("read committed %s: %v", genPath, err)
	}
	// Always restore the committed bytes, whether the assertion passes, fails,
	// or the regeneration errors partway.
	t.Cleanup(func() {
		if err := os.WriteFile(genPath, committed, 0o644); err != nil {
			t.Errorf("restore %s: %v", genPath, err)
		}
	})

	cmd := exec.Command("go", "run", "github.com/valyala/quicktemplate/qtc", "-dir=qtpl")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Skipf("qtc toolchain unavailable, skipping staleness guard: %v\n%s", err, out)
	}
	regenerated, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("read regenerated %s: %v", genPath, err)
	}
	// qtc emits an untagged file; genqtpl.go prepends the build constraint.
	want := append([]byte(qtplConstraint), regenerated...)
	if !bytes.Equal(committed, want) {
		t.Fatalf("%s is stale; regenerate with `cd bench && go generate ./...` (or `go run genqtpl.go`)", genPath)
	}
}
